<?php
namespace Drupal\spotify_lookup\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

class SpotifyApiConfigForm extends configFormBase {

  /**
   * @inerhitDoc
   */
  protected function getEditableConfigNames() {
    return ['spotify_lookup.api_keys'];
  }

  /**
   * @inerhitDoc
   */
  public function getFormId() {
    return 'spotify_api_form';
  }

  public function buildForm(array $form, FormStateInterface $form_state) {
    $config = $this->config('spotify_lookup.api_keys');

    $form['api_auth'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Spotify API Client ID'),
      '#description' => $this->t('Please provide the Spotify API Client ID from Spotify'),
      '#default_value' => $config->get('api_auth')
    ];
    $form['api_secret'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Spotify API Client Secret'),
      '#description' => $this->t('Please provide the Spotify API Client Secret from Spotify'),
      '#default_value' => $config->get('api_secret')
    ];
    return parent::buildForm($form, $form_state); // TODO: Change the autogenerated stub
  }
  public function submitForm(array &$form, FormStateInterface $form_state) {
    $this->config('spotify_lookup.api_keys')
      ->set('api_auth', $form_state->getValue('api_auth'))
      ->save();
    $this->config('spotify_lookup.api_keys')
      ->set('api_secret', $form_state->getValue('api_secret'))
      ->save();

    parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
  }
}
